projeto/urls.py
from django.contrib import admin
from django.urls import path
from estoque import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.produtos, name='produtos'),
    # path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    
    path('clientes/', views.clientes, name='clientes'),
    path('clientes/criar', views.criar_cliente, name='criar_cliente'),
    path('clientes/buscar', views.buscar_cliente, name='buscar_cliente'),
    path('clientes/editar/', views.editar_cliente, name='editar_cliente'),
    path('clientes/editar/<int:cliente_id>/', views.remover_cliente, name='remover_cliente'),

    path('produtos/', views.produtos, name='produtos'),
    path('produtos/criar', views.criar_produto, name='criar_produto'),
    path('produtos/buscar', views.buscar_produto, name='buscar_produto'),
    path('produtos/editar/', views.editar_produto, name='editar_produto'),
    path('produtos/editar/<int:produto_id>/', views.remover_produto, name='remover_produto'),
    path('produtos/relatorios', views.relatorios_produtos, name='relatorios_produtos'),

    path('vendas/', views.vendas, name='vendas'),
    path('vendas/criar', views.criar_venda, name='criar_venda'),
    path('buscar-cliente-venda/', views.buscar_cliente_venda, name='buscar_cliente_venda'),
    path('buscar-produto-venda/', views.buscar_produto_venda, name='buscar_produto_venda'),
    path('vendas/buscar/', views.buscar_venda, name='buscar_venda'),
    path('vendas/relatorios', views.relatorios_vendas, name='relatorios_vendas'),

    path('fornecedores/', views.fornecedores, name='fornecedores'),
    path('fornecedores/criar', views.criar_fornecedor, name='criar_fornecedor'),
    path('fornecedores/buscar', views.buscar_fornecedor, name='buscar_fornecedor'),
    path('fornecedores/editar/', views.editar_fornecedor, name='editar_fornecedor'),
    path('fornecedores/editar/<int:fornecedor_id>/', views.remover_fornecedor, name='remover_fornecedor'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

estoque/models.py
from django.db import models

class Produto(models.Model):
    nome = models.CharField(max_length=45, blank=False)
    preco = models.DecimalField(max_digits=9, decimal_places=2, blank=False)
    quantidade = models.IntegerField(blank=False)
    descricao = models.TextField(max_length=100, blank=True)
    categoria = models.TextField(max_length=60, blank=True)
    marca = models.TextField(max_length=40, blank=True)
    modelo = models.CharField(max_length=255, blank=True)
    imagem = models.ImageField(upload_to='produtos/', blank=True)
    fornecedor = models.ForeignKey('Fornecedor', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.nome
  
class Cliente(models.Model):
    nome = models.CharField(max_length=30, blank=False)
    cpf = models.CharField(max_length=14, blank=False)
    email = models.EmailField(max_length=30, blank=True)
    telefone = models.CharField(max_length=15, blank=True)
    endereco = models.CharField(max_length=50, blank=True)
    cidade = models.CharField(max_length=45, blank=True)
    estado = models.CharField(max_length=2, blank=True)
    cep = models.CharField(max_length=9, blank=True)

    def __str__(self):
        return self.nome
    
class Fornecedor(models.Model):
    nome = models.CharField(max_length=30, blank=False)
    cnpj = models.CharField(max_length=18, blank=False)
    email = models.EmailField(max_length=30, blank=True)
    telefone = models.CharField(max_length=15, blank=True)
    endereco = models.CharField(max_length=50, blank=True)
    cidade = models.CharField(max_length=45, blank=True)
    estado = models.CharField(max_length=2, blank=True)
    cep = models.CharField(max_length=9, blank=True)

    def __str__(self):
        return self.nome
    
class Venda(models.Model):
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    data = models.DateField(auto_now_add=True)
    valor = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    produtos = models.ManyToManyField('Produto', through='ItemVenda')
    desconto = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    opcoes_pagamento = (
        ('DINHEIRO', 'Dinheiro'),
        ('PIX', 'PIX'),
        ('CARTAO', 'Cartão'),
    )
    forma_pagamento = models.CharField(max_length=45, blank=False, choices=opcoes_pagamento)

class ItemVenda(models.Model):
    venda = models.ForeignKey('Venda', on_delete=models.CASCADE)
    produto = models.ForeignKey('Produto', on_delete=models.CASCADE)
    quantidade = models.IntegerField(blank=False)
    valor_unitario = models.DecimalField(max_digits=9, decimal_places=2, blank=False)

estoque/forms.py
import datetime
from django import forms

from estoque.models import Produto


class BuscarClienteForm(forms.Form):
    campo = forms.ChoiceField(choices=[
        ('todos', 'Todos os clientes'),
        ('id', 'ID'),
        ('nome', 'Nome'),
        ('cpf', 'CPF'),
        ('email', 'Email'),
        ('telefone', 'Telefone'),
        ('endereco', 'Endereço'),
        ('cidade', 'Cidade'),
        ('estado', 'Estado'),
        ('cep', 'CEP'),
    ])
    valor = forms.CharField(required=False)


class VendaForm(forms.Form):
    # Dados do cliente
    cpf = forms.CharField(label='CPF do Cliente', max_length=14, required=True, widget=forms.TextInput(attrs={'placeholder': 'XXX.XXX.XXX-XX', 'pattern': '[0-9]{11}', 'title': 'Digite apenas números'}))
    nome_cliente = forms.CharField(label='Nome do Cliente', required=False, disabled=True, widget=forms.TextInput(attrs={'readonly': True}))
    endereco = forms.CharField(label='Endereço', required=False, disabled=True, widget=forms.TextInput(attrs={'readonly': True}))
    cep = forms.CharField(label='CEP', required=False, disabled=True, widget=forms.TextInput(attrs={'readonly': True}))
    buscar_cliente = forms.CharField(label='', widget=forms.HiddenInput(), required=False)

    # Dados dos produtos
    produto_id = forms.IntegerField(label='ID do Produto', required=True)
    produto_nome = forms.CharField(label='Nome do Produto', required=False, disabled=True, widget=forms.TextInput(attrs={'readonly': True}))
    produto_preco = forms.DecimalField(label='Preço do Produto', required=False, disabled=True, widget=forms.TextInput(attrs={'readonly': True}))
    produto_estoque = forms.IntegerField(label='Quantidade em Estoque', required=False, disabled=True, widget=forms.TextInput(attrs={'readonly': True}))
    
    # Dados da venda
    data = forms.DateField(label='Data', widget=forms.DateInput(attrs={'type': 'date'}), initial=datetime.date.today)
    quantidade = forms.IntegerField(label='Quantidade', min_value=1, required=True, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    preco_total = forms.DecimalField(label='Preço Total', decimal_places=2, disabled=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    desconto = forms.DecimalField(label='Desconto em %', decimal_places=3, required=True, min_value=0, max_value=100,widget=forms.NumberInput(attrs={'class': 'form-control'}))
    opcoes_pagamento = (
        ('DINHEIRO', 'Dinheiro'),
        ('PIX', 'PIX'),
        ('CARTAO', 'Cartão'),
    )
    forma_pagamento = forms.ChoiceField(label='Forma de Pagamento', choices=opcoes_pagamento)

class BuscarVendaForm(forms.Form):
    campo = forms.ChoiceField(choices=[
        ('todos', 'Todas as vendas'),
        ('id', 'ID'),
        ('cpf', 'CPF do Cliente'),
        ('data', 'Data'),
        ('forma_pagamento', 'Forma de Pagamento'),
    ])
    valor = forms.CharField(required=False)

estoque/views.py
from datetime import datetime, timedelta
import os
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from estoque.forms import BuscarClienteForm, BuscarVendaForm, VendaForm
from estoque.models import Cliente, Fornecedor, ItemVenda, Produto, Venda

from projeto import settings
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.db.models import Q
from django.db.models import Sum


def home(request):
    context = {}
    return render(request, 'estoque/pages/home.html', context)

def categorias(request):
    context = {}
    return render(request, 'estoque/pages/categorias.html', context)

def clientes(request):
    total_clientes = Cliente.objects.all().count()
    context = {'total_clientes': total_clientes}
    return render(request, 'estoque/pages/clientes/clientes.html', context)

def criar_cliente(request):
    mensagem = None
    if request.method == 'POST':
        # Obtém os dados do formulário
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        cpf = request.POST.get('cpf')
        telefone = request.POST.get('telefone')
        endereco = request.POST.get('endereco')
        cidade = request.POST.get('cidade')
        estado = request.POST.get('estado')
        cep = request.POST.get('cep')
        
        if nome and cpf:
            novo_cliente = Cliente.objects.create(
                nome=nome,
                cpf=cpf,
                email=email,
                telefone=telefone,
                endereco=endereco,
                cidade=cidade,
                estado=estado,
                cep=cep
            )
            mensagem = "Cliente criado com sucesso!"
        else:
            mensagem = "Nome e CPF são campos obrigatórios."

    return render(request, 'estoque/pages/clientes/criar-cliente.html', {'mensagem': mensagem})

def buscar_cliente(request):
    form = BuscarClienteForm(request.GET)
    clientes = []

    if form.is_valid():
        campo = form.cleaned_data['campo']
        valor = form.cleaned_data['valor']

        if campo == 'todos':
            clientes = Cliente.objects.all()
        else:
            if campo and valor:
                filtros = {
                    'id': Cliente.objects.filter(id=valor),
                    'nome': Cliente.objects.filter(nome__icontains=valor),
                    'cpf': Cliente.objects.filter(cpf__icontains=valor),
                    'email': Cliente.objects.filter(email__icontains=valor),
                    'telefone': Cliente.objects.filter(telefone__icontains=valor),
                    'endereco': Cliente.objects.filter(endereco__icontains=valor),
                    'cidade': Cliente.objects.filter(cidade__icontains=valor),
                    'estado': Cliente.objects.filter(estado__icontains=valor),
                    'cep': Cliente.objects.filter(cep__icontains=valor),
                }
                clientes = filtros.get(campo, [])

    contexto = {'form': form, 'clientes': clientes, 'opcoes': form.fields['campo'].choices}

    return render(request, 'estoque/pages/clientes/buscar-cliente.html', contexto)

def editar_cliente(request):
    cliente = None
    sucesso = False
    if request.method == 'POST':
        cliente_id = request.POST.get('cliente_id')
        if cliente_id:
            cliente = get_object_or_404(Cliente, id=cliente_id)
        else:
            cliente_id = request.POST.get('cliente_id_hidden')
            cliente = get_object_or_404(Cliente, id=cliente_id)
            cliente.nome = request.POST.get('nome')
            cliente.email = request.POST.get('email')
            cliente.cpf = request.POST.get('cpf')
            cliente.telefone = request.POST.get('telefone')
            cliente.endereco = request.POST.get('endereco')
            cliente.cidade = request.POST.get('cidade')
            cliente.estado = request.POST.get('estado')
            cliente.cep = request.POST.get('cep')
            cliente.save()
            sucesso = True
            cliente = None

    return render(request, 'estoque/pages/clientes/editar-cliente.html', {'cliente': cliente, 'sucesso': sucesso})

def remover_cliente(request, cliente_id):
    deletado = False

    if request.method == 'POST':
        cliente = get_object_or_404(Cliente, id=cliente_id)
        cliente.delete()
        deletado = True

    return render(request, 'estoque/pages/clientes/editar-cliente.html', {'deletado': deletado})

def produtos(request):
    total_produtos = Produto.objects.all().count()
    context = {'total_produtos': total_produtos}
    return render(request, 'estoque/pages/produtos/produtos.html', context)

def criar_produto(request):
    mensagem = None
    if request.method == 'POST':
        # Obtém os dados do formulário
        nome = request.POST.get('nome')
        preco = request.POST.get('preco')
        quantidade = request.POST.get('quantidade')
        fornecedor_cnpj = request.POST.get('fornecedor')
        descricao = request.POST.get('descricao')
        categoria = request.POST.get('categoria')
        marca = request.POST.get('marca')
        modelo = request.POST.get('modelo')
        imagem = request.FILES.get('imagem')
        
        if nome and preco and quantidade:
            novo_produto = Produto.objects.create(
                nome=nome,
                preco=preco,
                quantidade=quantidade,
                descricao=descricao,
                categoria=categoria,
                marca=marca,
                modelo=modelo,
            )

            if fornecedor_cnpj:
                fornecedor, _ = Fornecedor.objects.get_or_create(cnpj=fornecedor_cnpj)
                novo_produto.fornecedor = fornecedor
                novo_produto.save()

            if imagem:
                filename, extension = os.path.splitext(imagem.name)
                imagem.name = f'produtos/{novo_produto.id}{extension}'
                novo_produto.imagem = imagem
                novo_produto.save()
            
            mensagem = "Produto criado com sucesso!"
        else:
            mensagem = "Nome, preço e quantidade são campos obrigatórios."

    return render(request, 'estoque/pages/produtos/criar-produto.html', {'mensagem': mensagem})

def buscar_produto(request):
    campo = request.GET.get('campo')
    valor = request.GET.get('valor')

    if campo == 'todos':
        produtos = Produto.objects.all()
    else:
        if campo and valor:
            filtros = {
                'id': Produto.objects.filter(id=valor),
                'nome': Produto.objects.filter(nome__icontains=valor),
                'preco': Produto.objects.filter(preco__icontains=valor),
                'quantidade': Produto.objects.filter(quantidade__icontains=valor),
                'descricao': Produto.objects.filter(descricao__icontains=valor),
                'categoria': Produto.objects.filter(categoria__icontains=valor),
                'marca': Produto.objects.filter(marca__icontains=valor),
                'modelo': Produto.objects.filter(modelo__icontains=valor),
            }
            produtos = filtros.get(campo, [])
     
        else:
            produtos = []

    campos_opcoes = {
        'todos': 'Todos os produtos',
        'id': 'ID',
        'nome': 'Nome',
        'preco': 'Preço',
        'quantidade': 'Quantidade',
        'descricao': 'Descrição',
        'categoria': 'Categoria',
        'marca': 'Marca',
        'modelo': 'Modelo',    
    }

    contexto = {'produtos': produtos, 'campo': campo, 'valor': valor}

    contexto['opcoes'] = campos_opcoes
    contexto['campo'] = campo if campo in campos_opcoes else 'todos'

    response = render(request, 'estoque/pages/produtos/buscar-produto.html', contexto)
    response['Cache-Control'] = 'must-revalidate'
    return response
    #return render(request, 'estoque/pages/produtos/buscar-produto.html', contexto)

def editar_produto(request):
    produto = None
    sucesso = False
    if request.method == 'POST':
        produto_id = request.POST.get('produto_id')
        if produto_id:
            produto = get_object_or_404(Produto, id=produto_id)
        else:
            produto_id = request.POST.get('produto_id_hidden')
            produto = get_object_or_404(Produto, id=produto_id)
            produto.nome = request.POST.get('nome')
            produto.preco = request.POST.get('preco')
            produto.quantidade = request.POST.get('quantidade')
            fornecedor_cnpj = request.POST.get('fornecedor')
            produto.descricao = request.POST.get('descricao')
            produto.categoria = request.POST.get('categoria')
            produto.marca = request.POST.get('marca')
            produto.modelo = request.POST.get('modelo')
            imagem = request.FILES.get('imagem')

            if fornecedor_cnpj:
                fornecedor, _ = Fornecedor.objects.get_or_create(cnpj=fornecedor_cnpj)
                produto.fornecedor = fornecedor

            if imagem:
                if produto.imagem: # Verifica se existe uma imagem
                    caminho_imagem = os.path.join(settings.MEDIA_ROOT, 'produtos', f'{produto_id}.png')
                    if os.path.exists(caminho_imagem): # Verifica se o arquivo da imagem existe
                        os.remove(caminho_imagem)
            
                nome_imagem = f'{produto_id}.png'
                caminho_imagem_nova = os.path.join(settings.MEDIA_ROOT, 'produtos', nome_imagem)
                default_storage.save(caminho_imagem_nova, ContentFile(imagem.read()))

                nome_imagem = f'{produto_id}.{imagem.name.split(".")[-1]}'  # ID_do_produto.formato
                caminho_imagem_nova = os.path.join(settings.MEDIA_ROOT, 'produtos', nome_imagem)
                default_storage.save(caminho_imagem_nova, imagem)
                
                # Atualize o campo 'imagem' do produto

estoque/templates/estoque/pages/vendas/buscar-venda.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-BR">
<head>
    {% include "estoque/partials/head.html" %}
    <title>{% block title %}Buscar Venda | Estoque++{% endblock title %}</title>
</head>

<body>
    {% include "estoque/partials/header.html" %}
    {% include "estoque/partials/header-vendas.html" %}

    <h2 class="textos">Buscar Venda:</h2>

    <div class="formulario-busca lexend-300">
        <form method="GET" action="{% url 'buscar_venda' %}">
            <select name="campo" id="campo">
                {% for campo_opcao, label in opcoes %}
                    <option value="{{ campo_opcao }}" {% if campo == campo_opcao %}selected{% endif %}>{{ label }}</option>
                {% endfor %}
            </select>
            <label for="valor">Valor:</label>
            <input type="text" id="valor" name="valor">
            <button type="submit" class="lexend-300">Buscar</button>
        </form>
    </div>

    {% if vendas %}
    <div class="resultado">
        <table class="tabela">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Data</th>
                    <th>Cliente</th>
                    <th>CPF</th>
                    <th>Telefone</th>
                    <th>Endereço</th>
                    <th>CEP</th>
                    <th>Estado</th>
                    <th>Nome Produto</th>
                    <th>Quantidade Produto</th>
                    <th>Preço Produto</th>
                    <th>Preço Final</th>
                    <th>Desconto</th>
                    <th>Forma de Pagamento</th>
                </tr>
            </thead>
            <tbody>
                {% for venda in vendas %}
                <tr>
                    <td>{{ venda.id }}</td>
                    <td>{{ venda.data }}</td>
                    <td>{{ venda.cliente.nome }}</td>
                    <td>{{ venda.cliente.cpf }}</td>
                    <td>{{ venda.cliente.telefone }}</td>
                    <td>{{ venda.cliente.endereco }}</td>
                    <td>{{ venda.cliente.cep }}</td>
                    <td>{{ venda.cliente.estado }}</td>
                    <td>
                        <ul class="listas">
                            {% for item in venda.itemvenda_set.all %}
                            <li>{{ item.produto.nome }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <ul class="listas">
                            {% for item in venda.itemvenda_set.all %}
                            <li>{{ item.quantidade }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <ul class="listas">
                            {% for item in venda.itemvenda_set.all %}
                            <li>{{ item.produto.preco }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>{{ venda.preco_final }}</td>
                    <td>{{ venda.desconto }}</td>
                    <td>{{ venda.forma_pagamento }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p class="textos">Nenhuma venda encontrada.</p>
    {% endif %}

</body>
</html>

estoque/templates/estoque/pages/vendas/criar-venda.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-BR">
<head>
    {% include "estoque/partials/head.html" %}
    <title>{% block title %}Criar Venda | Estoque++{% endblock title %}</title>
</head>

<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    
    {% include "estoque/partials/header.html" %}
    {% include "estoque/partials/header-vendas.html" %}
    
    <h2 class="textos">Criar Venda:</h2>

    {% if mensagem %}
        <p class="textos">{{ mensagem }}</p>
    {% endif %}

    <form action="{% url 'criar_venda' %}" method="POST" class="formulario lexend-300">
        {% csrf_token %}
        <p>Dados do Cliente: </p>
        <div class="form-group">
            {{ form.cpf.label_tag }}
            {{ form.cpf }}
            <button id="buscarClienteBtn" type="button" class="lexend-300">Buscar Cliente</button>
        </div>
        <p></p>
        <div class="form-group">
            {{ form.nome_cliente.label_tag }}
            {{ form.nome_cliente }}
        </div>
        <div class="form-group">
            {{ form.endereco.label_tag }}
            {{ form.endereco }}
        </div>
        <div class="form-group">
            {{ form.cep.label_tag }}
            {{ form.cep }}
        </div>

        <p>Dados dos Produtos:</p>
        <div class="form-group">
            {{ form.produto_id.label_tag }}
            {{ form.produto_id }}
            <button id="buscarProdutoBtn" class="lexend-300" type="button">Buscar Produto</button>   
        </div>
        <p></p>
        <div class="form-group">
            {{ form.produto_nome.label_tag }}
            {{ form.produto_nome }}
        </div>
        <div class="form-group">
            {{ form.produto_preco.label_tag }}
            {{ form.produto_preco }}
        </div>
        <div class="form-group">
            {{ form.produto_estoque.label_tag }}
            {{ form.produto_estoque }}
        </div>

        <p>Dados da Venda:</p>
        <div class="form-group">
            {{ form.data.label_tag }}
            {{ form.data }}
        <div class="form-group">
            {{ form.quantidade.label_tag }}
            {{ form.quantidade }}
        </div>
        <div class="form-group">
            {{ form.preco_total.label_tag }}
            {{ form.preco_total }}
        </div>
        <div class="form-group">
            {{ form.desconto.label_tag }}
            {{ form.desconto }}
        </div>
        <div class="form-group">
            {{ form.forma_pagamento.label_tag }}
            {{ form.forma_pagamento }}
        </div>
        <p></p>
        <button type="submit" class="lexend-300">Criar Venda</button>
    </form>
    
    <script>
        $(document).ready(function() { // Script para buscar cliente a partir do CPF
            $('#buscarClienteBtn').click(function() {
                var cpf = $('#id_cpf').val();
                if (cpf) {
                    $.ajax({
                        url: "/buscar-cliente-venda/",  // URL correspondente à view buscar_cliente_venda
                        type: "GET",
                        data: {'valor': cpf},
                        success: function(response) {
                            if (!response.error) {
                                $('#id_nome_cliente').val(response.nome_cliente);
                                $('#id_endereco').val(response.endereco);
                                $('#id_cep').val(response.cep);
                            } else {
                                alert(response.error);
                            }
                        },
                        error: function(xhr, errmsg, err) {
                            alert('Erro ao buscar cliente.');
                        }
                    });
                } else {
                    alert('Por favor, insira um CPF antes de buscar o cliente.');
                }
            });
        });

        $(document).ready(function() { // Script para buscar o produto a partir do ID
            $('#buscarProdutoBtn').click(function() {
                var produtoId = $('#id_produto_id').val();
                if (produtoId) {
                    $.ajax({
                        url: "/buscar-produto-venda/",  // URL correspondente à view para buscar o produto
                        type: "GET",
                        data: {'id': produtoId},
                        success: function(response) {
                            if (!response.error) {
                                // Preencher os campos do formulário com os dados do produto
                                $('#id_produto_nome').val(response.nome);
                                $('#id_produto_preco').val(response.preco);
                                $('#id_produto_estoque').val(response.estoque);
                            } else {
                                alert(response.error);
                            }
                        },
                        error: function(xhr, errmsg, err) {
                            alert('Erro ao buscar produto.');
                        }
                    });
                } else {
                    alert('Por favor, insira o ID do produto antes de buscar.');
                }
            });
        });

        $(document).ready(function() { // Script para calcular o preço total da venda
            $('#id_quantidade, #id_desconto').on('input', function() {
                var quantidade = parseInt($('#id_quantidade').val());
                var estoque = parseInt($('#id_produto_estoque').val());
                var precoUnitario = parseFloat($('#id_produto_preco').val());
                var desconto = parseFloat($('#id_desconto').val());

                if (!isNaN(quantidade) && !isNaN(precoUnitario)) {
                    if (quantidade > estoque) {
                        alert('Quantidade excede o estoque disponível.');
                        $('#id_quantidade').val(''); // Limpar o campo de quantidade
                    } 
                    else if (quantidade <= 0) {
                        alert('Quantidade deve ser um valor positivo.');
                        $('#id_quantidade').val(''); // Limpar o campo de quantidade
                    }
                    else {
                        var precoTotal = quantidade * precoUnitario;
                        if (!isNaN(desconto)) {
                            if(desconto >= 0 && desconto <= 100){
                                var precoComDesconto = precoTotal * (1 - desconto / 100);
                                $('#id_preco_total').val(precoComDesconto.toFixed(2));
                            }
                            else{
                                alert('Desconto deve ser um valor entre 0 e 100.');
                                $('#id_desconto').val(''); // Limpar o campo de desconto
                            }
                        }
                        else {
                            $('#id_preco_total').val(precoTotal.toFixed(2));
                        }
                    }
                }
            });
        });
    </script>

</body>
</html>

estoque/templates/estoque/pages/vendas/vendas.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-BR">
<head>
    {% include "estoque/partials/head.html" %}
    <title>{% block title %}Vendas | Estoque++{% endblock title %}</title>
</head>

<body>
    {% include "estoque/partials/header.html" %}
    {% include "estoque/partials/header-vendas.html" %}
    
    <p class="textos lexend-400">Total de vendas: {{ total_vendas }}</p>
</body>
</html>